from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate 
from dotenv import load_dotenv
from frontend import user_query
from query_model import get_query

load_dotenv()

response_sys_message = """
You are a part of an AI agent named "Campus Chatbot"
Task: Your task is to understand the user query and reply in natural language
Inputs: You will get a question from user and a dataframe from SQL database. The dataframe is retieved through SELECT queries generated by previous model. You have to understand the users query and look into retrieved data to reply in natural language as their friend
"""

human_message = """
User query is: {user_query} 
The data retrieved is: {data}
"""
def final_response(user_query):
    query_result = get_query(user_query=user_query,max_retries=3)

    response_model = ChatGoogleGenerativeAI(model='gemini-2.5-flash',temperature=0.8)
    response_template = ChatPromptTemplate([
        ('system',response_sys_message),
        ('human',human_message)
    ])

    response_prompt=response_template.invoke({
        'user_query':user_query,
        'data':query_result
    })


    response = response_model.invoke(response_prompt)
    return response.content