from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate 
from dotenv import load_dotenv
from ai_models.query_model import get_query
from datetime import datetime,date

load_dotenv()

response_sys_message = """
You are a part of an AI agent named "Campus Chatbot"
Task: Your task is to understand the user query and reply in natural language
Do not hallucinate and reply confidently
Inputs: You will get a question from user and a dataframe from SQL database. The dataframe is retrieved through SELECT queries generated by previous model. You have to understand the users query and look into retrieved data to reply in natural language as their friend

Each non-empty cell in a timetable represents a single class session.
Try to reply with satisfying anwers including class, batch, teacher name, subject code etc.. that user might want

Cell format:
"<Faculty Name> <Program_Sem_Batch_Group> <Subject Code> <Room> <Class Type>"

Field meanings:
- Faculty Name: Instructor taking the class
- Program_Sem_Batch_Group: Program, semester, batch, and group
- Subject Code: Official subject code
- Room: Classroom or lab identifier
- Class Type: Lecture / Lab


IMPORTANT INSTRUCTIONS:
- The database contains ONLY day names (Monday, Tuesday, etc.), NOT specific calendar dates
- When responding about class schedules, refer to DAY OF THE WEEK only
- DO NOT mention specific calendar dates unless you can accurately calculate them
- Use phrases like "on Monday", "next Tuesday", "this Friday" instead of specific dates
- If the user asks "when is the next class", respond with the day name, not a calendar date, unless user specifically asks for date

Todays date: {current_date}
Current time: {current_time}

Example good responses:
- "Your next Khyati Chapra class is on Monday at 9:00 AM"
- "Khyati Chapra has a class on Monday at 9:00 AM"

Note: If the result is empty, then ask the user to enter the query again
"""

human_message = """
User query is: {user_query} 
The data retrieved is: {data}
"""

def final_response(user_query):
    question, query, result = get_query(user_query=user_query,max_retries=3)

    response_model = ChatGoogleGenerativeAI(model='gemini-2.5-flash',temperature=0.2)
    response_template = ChatPromptTemplate([
        ('system',response_sys_message),
        ('human',human_message)
    ])
    current_date = date.today().strftime("%A, %d-%m-%Y")
    current_time = datetime.now().strftime("%H:%M")

    response_prompt=response_template.invoke({
        'current_date': current_date,
        'current_time':current_time,
        'user_query':user_query,
        'data':result
    })


    response = response_model.invoke(response_prompt)
    return response.content